#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from grako.buffering import Buffer
from grako.parsing import graken, Parser
from grako.util import re, RE_FLAGS, generic_main  # noqa


KEYWORDS = {}


class DanmuBuffer(Buffer):
    def __init__(
        self,
        text,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re=None,
        ignorecase=None,
        namechars='',
        **kwargs
    ):
        super(DanmuBuffer, self).__init__(
            text,
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            namechars=namechars,
            **kwargs
        )


class DanmuParser(Parser):
    def __init__(
        self,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re=None,
        ignorecase=None,
        left_recursion=False,
        parseinfo=True,
        keywords=None,
        namechars='',
        buffer_class=DanmuBuffer,
        **kwargs
    ):
        if keywords is None:
            keywords = KEYWORDS
        super(DanmuParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            parseinfo=parseinfo,
            keywords=keywords,
            namechars=namechars,
            buffer_class=buffer_class,
            **kwargs
        )

    @graken()
    def _start_(self):
        self._array_()
        self._check_eof()

    @graken()
    def _array_(self):

        def block0():
            self._item_()
        self._positive_closure(block0)

    @graken()
    def _item_(self):
        with self._group():
            with self._choice():
                with self._option():
                    self._pair_()
                with self._option():
                    self._data_()
                self._error('no available options')
        self._token('/')

    @graken()
    def _pair_(self):
        self._key_()
        self._token('@=')
        self._data_()

    @graken()
    def _key_(self):
        self._pattern(r'[^@/]+')

    @graken()
    def _data_(self):

        def block0():
            self._char_()
        self._closure(block0)

    @graken()
    def _char_(self):
        self._pattern(r'(@S|@A|[^@/])')


class DanmuSemantics(object):
    def start(self, ast):
        return ast

    def array(self, ast):
        return ast

    def item(self, ast):
        return ast

    def pair(self, ast):
        return ast

    def key(self, ast):
        return ast

    def data(self, ast):
        return ast

    def char(self, ast):
        return ast


def main(filename, startrule, **kwargs):
    with open(filename) as f:
        text = f.read()
    parser = DanmuParser()
    return parser.parse(text, startrule, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from grako.util import asjson

    ast = generic_main(main, DanmuParser, name='Danmu')
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(asjson(ast), indent=2))
    print()

